services:
  db:
    container_name: db-jr-dashboard
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_insurance_dashboard
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - jr-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma-jr-dashboard
    ports:
      - "8080:80"
    restart: always
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 100M
    depends_on:
      - db
    networks:
      - jr-net

volumes:
  mysql_data:


networks:
  jr-net:
    driver: bridge
